// <auto-generated />
using System;
using JuliePro.Models.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JuliePro.Migrations
{
    [DbContext(typeof(JulieProDbContext))]
    [Migration("20250624011431_CustomerObjectif")]
    partial class CustomerObjectif
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JuliePro.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("StartWeight")
                        .HasColumnType("float");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            BirthDate = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "alice@juliepro.ca",
                            FirstName = "Alice",
                            LastName = "Smith",
                            StartWeight = 150.0
                        },
                        new
                        {
                            CustomerId = 2,
                            BirthDate = new DateTime(1985, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "bob@juliepro.ca",
                            FirstName = "Bob",
                            LastName = "Brown",
                            StartWeight = 180.0
                        },
                        new
                        {
                            CustomerId = 3,
                            BirthDate = new DateTime(1992, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "carol@juliepro.ca",
                            FirstName = "Carol",
                            LastName = "Johnson",
                            StartWeight = 140.0
                        },
                        new
                        {
                            CustomerId = 4,
                            BirthDate = new DateTime(1988, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "david@juliepro.ca",
                            FirstName = "David",
                            LastName = "Davis",
                            StartWeight = 200.0
                        });
                });

            modelBuilder.Entity("JuliePro.Models.Objective", b =>
                {
                    b.Property<int>("ObjectiveId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ObjectiveId"));

                    b.Property<DateTime?>("AchievedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<double>("DistanceKm")
                        .HasColumnType("float");

                    b.Property<double>("LostWeightKg")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ObjectiveId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Objectives");

                    b.HasData(
                        new
                        {
                            ObjectiveId = 1,
                            CustomerId = 1,
                            DistanceKm = 0.0,
                            LostWeightKg = 5.0,
                            Name = "Perte 5kg"
                        },
                        new
                        {
                            ObjectiveId = 2,
                            AchievedDate = new DateTime(2025, 3, 23, 21, 14, 30, 619, DateTimeKind.Local).AddTicks(5981),
                            CustomerId = 1,
                            DistanceKm = 5.0,
                            LostWeightKg = 0.0,
                            Name = "Course 5km"
                        },
                        new
                        {
                            ObjectiveId = 3,
                            AchievedDate = new DateTime(2025, 4, 23, 21, 14, 30, 621, DateTimeKind.Local).AddTicks(6930),
                            CustomerId = 1,
                            DistanceKm = 0.0,
                            LostWeightKg = 3.0,
                            Name = "Perte 3kg"
                        },
                        new
                        {
                            ObjectiveId = 4,
                            AchievedDate = new DateTime(2025, 5, 23, 21, 14, 30, 621, DateTimeKind.Local).AddTicks(6941),
                            CustomerId = 1,
                            DistanceKm = 10.0,
                            LostWeightKg = 0.0,
                            Name = "Course 10km"
                        },
                        new
                        {
                            ObjectiveId = 5,
                            CustomerId = 2,
                            DistanceKm = 0.0,
                            LostWeightKg = 7.0,
                            Name = "Perte 7kg"
                        },
                        new
                        {
                            ObjectiveId = 6,
                            CustomerId = 2,
                            DistanceKm = 8.0,
                            LostWeightKg = 0.0,
                            Name = "Course 8km"
                        },
                        new
                        {
                            ObjectiveId = 7,
                            AchievedDate = new DateTime(2025, 2, 23, 21, 14, 30, 621, DateTimeKind.Local).AddTicks(6946),
                            CustomerId = 3,
                            DistanceKm = 6.0,
                            LostWeightKg = 0.0,
                            Name = "Course 6km"
                        },
                        new
                        {
                            ObjectiveId = 8,
                            AchievedDate = new DateTime(2025, 3, 23, 21, 14, 30, 621, DateTimeKind.Local).AddTicks(6948),
                            CustomerId = 3,
                            DistanceKm = 0.0,
                            LostWeightKg = 4.0,
                            Name = "Perte 4kg"
                        },
                        new
                        {
                            ObjectiveId = 9,
                            CustomerId = 4,
                            DistanceKm = 12.0,
                            LostWeightKg = 0.0,
                            Name = "Course 12km"
                        },
                        new
                        {
                            ObjectiveId = 10,
                            AchievedDate = new DateTime(2025, 4, 23, 21, 14, 30, 621, DateTimeKind.Local).AddTicks(6950),
                            CustomerId = 4,
                            DistanceKm = 0.0,
                            LostWeightKg = 6.0,
                            Name = "Perte 6kg"
                        });
                });

            modelBuilder.Entity("JuliePro.Models.Speciality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Specialities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Perte de poids"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Course"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Halthérophilie"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Réhabilitation"
                        });
                });

            modelBuilder.Entity("JuliePro.Models.Trainer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("SpecialityId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SpecialityId");

                    b.ToTable("Trainer");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "Chrystal.lapierre@juliepro.ca",
                            FirstName = "Chrystal",
                            LastName = "Lapierre",
                            Photo = "Chrystal.png",
                            SpecialityId = 1
                        },
                        new
                        {
                            Id = 2,
                            Email = "Felix.trudeau@juliePro.ca",
                            FirstName = "Félix",
                            LastName = "Trudeau",
                            Photo = "Felix.png",
                            SpecialityId = 2
                        },
                        new
                        {
                            Id = 3,
                            Email = "Frank.StJohn@juliepro.ca",
                            FirstName = "François",
                            LastName = "Saint-John",
                            Photo = "Francois.png",
                            SpecialityId = 1
                        },
                        new
                        {
                            Id = 4,
                            Email = "JC.Bastien@juliepro.ca",
                            FirstName = "Jean-Claude",
                            LastName = "Bastien",
                            Photo = "JeanClaude.png",
                            SpecialityId = 4
                        },
                        new
                        {
                            Id = 5,
                            Email = "JinLee.godette@juliepro.ca",
                            FirstName = "Jin Lee",
                            LastName = "Godette",
                            Photo = "Jin Lee.png",
                            SpecialityId = 3
                        },
                        new
                        {
                            Id = 6,
                            Email = "Karine.Lachance@juliepro.ca",
                            FirstName = "Karine",
                            LastName = "Lachance",
                            Photo = "Karine.png",
                            SpecialityId = 2
                        },
                        new
                        {
                            Id = 7,
                            Email = "Ramone.Esteban@juliepro.ca",
                            FirstName = "Ramone",
                            LastName = "Esteban",
                            Photo = "Ramone.png",
                            SpecialityId = 3
                        });
                });

            modelBuilder.Entity("JuliePro.Models.Objective", b =>
                {
                    b.HasOne("JuliePro.Models.Customer", "Customer")
                        .WithMany("Objectives")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("JuliePro.Models.Trainer", b =>
                {
                    b.HasOne("JuliePro.Models.Speciality", "speciality")
                        .WithMany()
                        .HasForeignKey("SpecialityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("speciality");
                });

            modelBuilder.Entity("JuliePro.Models.Customer", b =>
                {
                    b.Navigation("Objectives");
                });
#pragma warning restore 612, 618
        }
    }
}
